# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='account/images/user-default.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
