# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/user-default.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
